# Generated by Django 4.2.14 on 2024-08-05 09:20

from django.db import migrations, models
import django.db.models.deletion
import pupils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('pupil_phone', models.CharField(max_length=12, unique=True, validators=[pupils.models.validate_phone])),
                ('parent_phone', models.CharField(max_length=12, unique=True, validators=[pupils.models.validate_phone])),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
        ),
    ]
