# Generated by Django 4.2.14 on 2024-08-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
