# Generated by Django 4.2.14 on 2024-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0002_alter_pupil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
