# Generated by Django 4.2.14 on 2024-08-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='day',
            field=models.BooleanField(),
        ),
    ]
